// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"

	"github.com/lc-tut/hdd-music-web/internal/entity"
)

const createMusicRow = `-- name: CreateMusicRow :one
INSERT INTO musics (
    title, midi_file_path
) VALUES (
    $1, $2
) RETURNING id, midi_file_path
`

type CreateMusicRowParams struct {
	Title        string `json:"title"`
	MidiFilePath string `json:"midi_file_path"`
}

type CreateMusicRowRow struct {
	ID           pgtype.UUID `json:"id"`
	MidiFilePath string      `json:"midi_file_path"`
}

func (q *Queries) CreateMusicRow(ctx context.Context, arg CreateMusicRowParams) (CreateMusicRowRow, error) {
	row := q.db.QueryRow(ctx, createMusicRow, arg.Title, arg.MidiFilePath)
	var i CreateMusicRowRow
	err := row.Scan(&i.ID, &i.MidiFilePath)
	return i, err
}

const getMusicMovies = `-- name: GetMusicMovies :one
SELECT title, created_at, updated_at FROM musics
WHERE movie_file_path IS NOT NULL
AND movie_file_path != ''
ORDER BY created_at DESC
`

type GetMusicMoviesRow struct {
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetMusicMovies(ctx context.Context) (GetMusicMoviesRow, error) {
	row := q.db.QueryRow(ctx, getMusicMovies)
	var i GetMusicMoviesRow
	err := row.Scan(&i.Title, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getMusicRowByID = `-- name: GetMusicRowByID :many
SELECT id, title, midi_file_path, movie_file_path, created_at, updated_at FROM musics WHERE id = $1
`

func (q *Queries) GetMusicRowByID(ctx context.Context, id pgtype.UUID) ([]entity.Music, error) {
	rows, err := q.db.Query(ctx, getMusicRowByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []entity.Music{}
	for rows.Next() {
		var i entity.Music
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.MidiFilePath,
			&i.MovieFilePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMusic_movieFilePath = `-- name: UpdateMusic_movieFilePath :one
UPDATE musics
SET movie_file_path = $2
WHERE id = $1
RETURNING id, movie_file_path
`

type UpdateMusic_movieFilePathParams struct {
	ID            pgtype.UUID `json:"id"`
	MovieFilePath pgtype.Text `json:"movie_file_path"`
}

type UpdateMusic_movieFilePathRow struct {
	ID            pgtype.UUID `json:"id"`
	MovieFilePath pgtype.Text `json:"movie_file_path"`
}

func (q *Queries) UpdateMusicMovieFilePath(ctx context.Context, arg UpdateMusic_movieFilePathParams) (UpdateMusic_movieFilePathRow, error) {
	row := q.db.QueryRow(ctx, updateMusic_movieFilePath, arg.ID, arg.MovieFilePath)
	var i UpdateMusic_movieFilePathRow
	err := row.Scan(&i.ID, &i.MovieFilePath)
	return i, err
}
