// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package entity

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Music struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	MidiFilePath  string             `json:"midi_file_path"`
	MovieFilePath string       `json:"movie_file_path"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
